#This is a Snakefile for analyzing FlashSeq Low amplification data containing 3 steps
import pandas as pd
import os

# -- Rule files -- #
include: "rules/common.smk"
include: "rules/cat.smk"
include: "rules/align.smk"
include: "rules/featurecounts.smk"
include: "rules/multiqc.smk"

# Variable declaration
OUTDIR = config["out"]
TEMPDIR = config["temp"]
#LOGDIR = config["log"]

# -- Final output -- #
rule all:
    input:
        expand("{TEMPDIR}/counts/{sample}_ReadCount.featureCounts.gencode.txt", sample=samples['sampleName'], TEMPDIR=TEMPDIR),"qc/multiqc_report.html"

